<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="2" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="228" started-at="2020-09-26T16:54:47Z" finished-at="2020-09-26T16:54:47Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="228" started-at="2020-09-26T16:54:47Z" finished-at="2020-09-26T16:54:47Z">
      <class name="com.qa.testNGFeatures.testNG_Features">
        <test-method status="PASS" signature="login_page()[pri:0, instance:com.qa.testNGFeatures.testNG_Features@1057a39]" name="login_page" duration-ms="53" started-at="2020-09-26T16:54:47Z" finished-at="2020-09-26T16:54:47Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at com.qa.testNGFeatures.testNG_Features.login_page(testNG_Features.java:10)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_page -->
        <test-method status="PASS" signature="home_page()[pri:0, instance:com.qa.testNGFeatures.testNG_Features@1057a39]" name="home_page" duration-ms="5" started-at="2020-09-26T16:54:47Z" depends-on-methods="com.qa.testNGFeatures.testNG_Features.login_page" finished-at="2020-09-26T16:54:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- home_page -->
      </class> <!-- com.qa.testNGFeatures.testNG_Features -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
